name: Run Selenium Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */2 * * *"  # Runs every 6 hours (adjust as needed)
  workflow_dispatch:  # Allows manual execution

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          python -m pip install --upgrade pip
          pip install -r requirements.txt --force-reinstall


      - name: Run Selenium bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          PROXY_PASS: ${{ secrets.PROXY_PASS }}
        run: xvfb-run --auto-servernum python adsjshsbchdbcdbkc.py  # Run script with virtual display
